# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: notes
site_url: https://192.168.0.1/notes
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
  icon:
    admonition:
      note: material/alert
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: 4051B5
      accent: 4051B5

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
        primary: blue
        accent: deep orange

markdown_extensions:
  - tables
  - toc
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true


extra_css:

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search