openapi: 3.0.1
info:
  title: Camera system backend API
  description: API documentation for the backend REST API
  version: "1.0.0"
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /alive:
    get:
      tags:
        - Utilities
      summary: Alive ping for checking server health
      responses:
        "200":
          description: Server is alive
          content:
            application/json:
              schema:
                type: string
                example: "Alive!"
  /tapo-320ws/info/{name}:
    get:
      tags:
        - Tapo320WS
      summary: Retrieve camera info
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Camera information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_info:
                    type: object
                    properties:
                      basic_info:
                        type: object
                        properties:
                          device_type: { type: string }
                          device_info: { type: string }
                          features: { type: number }
                          barcode: { type: string }
                          device_model: { type: string }
                          sw_version: { type: string }
                          device_name: { type: string }
                          hw_version: { type: string }
                          device_alias: { type: string }
                          mobile_access: { type: number }
                          mac: { type: string }
                          dev_id: { type: string }
                          hw_id: { type: string }
                          oem_id: { type: string }
                          hw_desc: { type: string }
                          manufacturer_name: { type: string }
                          region: { type: string }
                          ffs: { type: boolean }
                          is_cal: { type: boolean }
                          avatar: { type: string }
                          has_set_location_info: { type: number }
                          longitude: { type: number }
                          latitude: { type: number }
  /tapo-320ws/light/{name}:
    get:
      tags:
        - Tapo320WS
      summary: Get light status
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Light status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: number }
                  rest_time: { type: number }
    post:
      tags:
        - Tapo320WS
      summary: Change light status
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Light status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: number }
                  rest_time: { type: number }
  /tapo-320ws/night/{name}:
    get:
      tags:
        - Tapo320WS
      summary: Get night-vision status
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Night-vision status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: number }
    post:
      tags:
        - Tapo320WS
      summary: Change night-vision status
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Night-vision status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: number }
  /tapo-320ws/stream/{name}:
    get:
      tags:
        - Tapo320WS
      summary: Get stream WebSocket URL
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Stream URL retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  streamUrl:
                    type: string
                    example: "ws://"
  /tapo-320ws/recordings/{name}:
    get:
      tags:
        - Tapo320WS
      summary: Get recordings
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the camera
          schema:
            type: string
      responses:
        "200":
          description: Recordings retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    startTime: { type: string, example: "14:47:43" }
                    endTime: { type: string, example: "14:48:50" }
                    vedio_type: { type: number }
                    duration_seconds: { type: number }
                    date: { type: string, example: "2024-12-26" }
                    id: { type: string }
                    downloaded: { type: boolean }
